### ISSUE TITLE
What is 'opt' in the train.py?

### ISSUE THREAD

**Issue by Ridhee** [dv-fenix/HyperspecAE#1]
Code is excellent. I just want to know what is 'opt' in train.py

what argument should I pass when I am calling train module.

Thank you

**Comment by dv-fenix** [comment]
Hi @Ridhee,

`opt` in `train.py` contains all the arguments parsed from the command line.

I have provided an example training script [here](https://github.com/dv-fenix/HyperspecAE/blob/main/run/samson_train.sh). To explore more experimental setups, I will encourage you to have a look at [opts.py](https://github.com/dv-fenix/HyperspecAE/blob/main/src/utils/opts.py) and go through all the available command line arguments. This will further help you write your own custom training bash script.

Hope that answers your queries.

**Comment by Ridhee** [comment]
Thank you.
